# Generated by Django 3.1.1 on 2020-10-02 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200930_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='xml',
            field=models.FileField(default=django.utils.timezone.now, upload_to='books/pdfs/'),
            preserve_default=False,
        ),
    ]
