# Generated by Django 3.1.1 on 2020-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_article_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='xml',
            field=models.FileField(upload_to='media/xml'),
        ),
    ]
