# Generated by Django 3.1.1 on 2020-10-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201002_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XmlFile',
            new_name='File',
        ),
    ]
